### ISSUE TITLE
pj_dump seems to drop events

### ISSUE THREAD

**Issue by Shurakai** [schnorr/pajeng#14]
Today I realized that the pj_dump seems to loose some states somewhere. Here is what I do:

Run SMPI with TI traces on 12 processes. Run grep and search for "finalize": It reports 12 occurrences.

Run SMPI replay and write paje file to a file called "smpi_replay_output". Run grep and search for finalize returns only one line here.
 
   5 12 2 smpi_replay_run_finalize "0 1 0"

This line looks good to me.

Then run pj_dump on the file smpi_replay_output and grep for "finalize": It returns 11 occurrences, but it should return 12 (remember: the TI traces DID contain 12 occurrences!).

This is how I use pj_dump:

   pj_dump --ignore-incomplete-links replay_output >| replay.paje.dump

I'm not sure why this is happening, but maybe someone here cares - I think it should still contain 12 occurrences.

**Comment by schnorr** [comment]
Can you provide the original paje trace file so we can reproduce the
probable error here? Another possibility is that the tracer is not
registering in the trace the 12th event.

**Comment by Shurakai** [comment]
Definitely. It's just 117 MB large - so I copied it to your Grid5k home account in Lyon. It's called "replay_output".

**Comment by schnorr** [comment]
Thanks for the file and for the bug report. There was indeed a problem: it wasn't in the core, but in the query API of libPaje. Commit 6b24ad820e3cde4be1d5b6664c9b20a127d25b70 should fix it. Reopen if don't.
