### ISSUE TITLE
ctest is failing

### ISSUE THREAD

**Issue by afarah1** [schnorr/pajeng#17]
7/12 Test  #7: pj_dump_small ....................***Failed    0.13 sec

More precisely, `./pj_dump ../traces/events.trace` gives

    PajeSimulationException: Illegal, container events are not time-ordered in (Line: 147, Fields: '4, Contents: '7 1.340000000 PROCESS p1')

Instead of what is expected in the `.tesh` file.

**Comment by schnorr** [comment]
I have just run a ctest command but there is no problem. Can you confirm this is also the case for you?

**Comment by afarah1** [comment]
It's working now.
