### ISSUE TITLE
pj_validate was removed, drop mentions of it

### ISSUE THREAD

**Issue by mquinson** [schnorr/pajeng#19]
Hello, 

we received this bug from the bug tracking system.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827793

I will remove it from the package description, but I think you should remove it from the doc.

Thanks,

**Comment by schnorr** [comment]
Done at 695818664dc4c7c03cbf598a209ba272bce70151 and 462b2eace85cc0b803326b18a80c5d0259867763.
