### ISSUE TITLE
libpaje dependency

### ISSUE THREAD

**Issue by dosimont** [schnorr/pajeng#20]
pj_dump is linked to the libpaje library that is present in the compilation directory, and not to the one that is installed. Exemple of ldd command result:

>ldd /opt/paje/pajeng/bin/pj_dump
>	linux-vdso.so.1 (0x00007ffdc7326000)
>	libpaje.so.2 => /home/dosimont/Git/programs/schnorr/pajeng/build/src/libpaje/libpaje.so.2 (0x00007f8e87fd4000)
>	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8e87c32000)
>	libm.so.6 => /lib64/libm.so.6 (0x00007f8e87930000)
>	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8e87719000)
>	libc.so.6 => /lib64/libc.so.6 (0x00007f8e87357000)
>	/lib64/ld-linux-x86-64.so.2 (0x000055b0525df000)

pj_dump and the other tools relying on libpaje should use the installed version of the library. This can be done by setting properly rpath in cmake

**Comment by schnorr** [comment]
Hi, could you provide a patch or issue a pull request fixing this problem? I'll be very happy. ;-)

**Comment by dosimont** [comment]
I've started to take a look on this issue. However, this will require to modify a bit the cmake building structure, by using CMake subprojects instead of just one root project. Of course, this will involve many changes. I will try to find the time to do that.

**Comment by schnorr** [comment]
I see your point, but debian packaging works. So I think this is not a problem. Perhaps @mquinson could clarify this for us.

**Comment by mquinson** [comment]
My point is that the simpler, the better. My experience with cmake is that you don't want to be cleaver (nor violent) with it. Stick to the simple mainstream solutions, and have a pleasant and productive day.

Bye, Mt.
